eUcionica/Pages/OblastPage/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using DataBaseContext;
using DatabaseEntityLib;

namespace eUcionica.Pages.OblastPage
{
    public class CreateModel : PageModel
    {
        private readonly DataBaseContext.DB_Context_Class _context;

        public CreateModel(DataBaseContext.DB_Context_Class context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["PredmetID"] = new SelectList(_context.Predmet, "ID", "Name");
            return Page();
        }

        [BindProperty]
        public Oblast Oblast { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (/*!ModelState.IsValid ||*/ _context.Oblast == null || Oblast == null)
            {
                return Page();
            }

            _context.Oblast.Add(Oblast);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Oblasti");
        }
    }
}

eUcionica/Pages/OblastPage/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DataBaseContext;
using DatabaseEntityLib;

namespace eUcionica.Pages.OblastPage
{
    public class DeleteModel : PageModel
    {
        private readonly DataBaseContext.DB_Context_Class _context;

        public DeleteModel(DataBaseContext.DB_Context_Class context)
        {
            _context = context;
        }

        [BindProperty]
      public Oblast Oblast { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Oblast == null)
            {
                return NotFound();
            }

            var oblast = await _context.Oblast
                .Include(o => o.Predmet)
                .FirstOrDefaultAsync(m => m.ID == id);

            if (oblast == null)
            {
                return NotFound();
            }
            else 
            {
                Oblast = oblast;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Oblast == null)
            {
                return NotFound();
            }
            var oblast = await _context.Oblast.FindAsync(id);

            if (oblast != null)
            {
                Oblast = oblast;
                _context.Oblast.Remove(Oblast);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Oblasti");
        }
    }
}

eUcionica/Pages/PitanjePage/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using DataBaseContext;
using DatabaseEntityLib;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Hosting.Server;
using System.IO;

namespace eUcionica.Pages.PitanjePage
{
    public class CreateModel : PageModel
    {
        private readonly DataBaseContext.DB_Context_Class _context;
        private IWebHostEnvironment _environment;

        public CreateModel(DataBaseContext.DB_Context_Class context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        [BindProperty]
        public Pitanje Pitanje { get; set; } = default!;

        public SelectList PredmetOptions { get; set; }
        public SelectList OblastOptions { get; set; }

        public SelectList DifficultyOptions { get; set; }

        [BindProperty]
        public IFormFile? Upload { get; set; }

        public IActionResult OnGet()
        {
            PredmetOptions = new SelectList(_context.Predmet, "ID", "Name");
            ViewData["PredmetID"] = PredmetOptions;

            OblastOptions = new SelectList(Enumerable.Empty<Oblast>(), "ID", "Name");
            ViewData["OblastID"] = OblastOptions;

            var uniqueDifficulties = _context.Pitanje.Select(p => p.Difficulty).Distinct().ToList();
            DifficultyOptions = new SelectList(uniqueDifficulties);
            ViewData["Difficulty"] = DifficultyOptions;



            return Page();
        }

        public JsonResult OnGetIzaberiOblasti(int predmetID)
        {

            var oblasti = _context.Oblast
                .Where(o => o.PredmetID == predmetID)
                .Select(o => new { id = o.ID, name = o.Name })
                .ToList();

            return new JsonResult(oblasti);
        }


        public async Task<IActionResult> OnPostAsync()
        {
            if ( _context.Pitanje == null || Pitanje == null)
            {
                return Page();
            }
            

            if (Upload != null)
            {
                var file = Path.Combine(_environment.ContentRootPath, "wwwroot\\images", Upload.FileName);
                using (var fileStream = new FileStream(file, FileMode.Create))
                {
                    await Upload.CopyToAsync(fileStream);

                    Pitanje.Image = Upload.FileName;
                }
            }



            _context.Pitanje.Add(Pitanje);
             await _context.SaveChangesAsync();
            
             return RedirectToPage("./Pitanja");
        }
    }
}

eUcionica/Pages/PitanjePage/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DataBaseContext;
using DatabaseEntityLib;

namespace eUcionica.Pages.PitanjePage
{
    public class DeleteModel : PageModel
    {
        private readonly DataBaseContext.DB_Context_Class _context;

        public DeleteModel(DataBaseContext.DB_Context_Class context)
        {
            _context = context;
        }

        [BindProperty]
      public Pitanje Pitanje { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Pitanje == null)
            {
                return NotFound();
            }

            var pitanje = await _context.Pitanje
                .Include(p => p.Oblast)
                .Include(p => p.Predmet)
                .FirstOrDefaultAsync(m => m.ID == id);

            if (pitanje == null)
            {
                return NotFound();
            }
            else 
            {
                Pitanje = pitanje;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Pitanje == null)
            {
                return NotFound();
            }
            var pitanje = await _context.Pitanje
                .FindAsync(id);

            if (pitanje != null)
            {
                Pitanje = pitanje;
                _context.Pitanje.Remove(Pitanje);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Pitanja");
        }
    }
}

eUcionica/Pages/PitanjePage/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DataBaseContext;
using DatabaseEntityLib;

namespace eUcionica.Pages.PitanjePage
{
    public class DetailsModel : PageModel
    {
        private readonly DataBaseContext.DB_Context_Class _context;

        public DetailsModel(DataBaseContext.DB_Context_Class context)
        {
            _context = context;
        }

      public Pitanje Pitanje { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Pitanje == null)
            {
                return NotFound();
            }

            var pitanje = await _context.Pitanje
                .Include(p => p.Oblast)
                .Include(p => p.Predmet)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (pitanje == null)
            {
                return NotFound();
            }
            else 
            {
                Pitanje = pitanje;
            }
            return Page();
        }
    }
}

eUcionica/Pages/PitanjePage/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataBaseContext;
using DatabaseEntityLib;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Hosting.Server;
using System.IO;
using System.Net;

namespace eUcionica.Pages.PitanjePage
{
    public class EditModel : PageModel
    {
        private readonly DataBaseContext.DB_Context_Class _context;
        private IWebHostEnvironment _environment;

        public EditModel(DataBaseContext.DB_Context_Class context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        [BindProperty]
        public Pitanje Pitanje { get; set; } = default!;

        public SelectList DifficultyOptions { get; set; }

        [BindProperty]
        public IFormFile? Upload { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Pitanje == null)
            {
                return NotFound();
            }

            var pitanje =  await _context.Pitanje
                .Include(p => p.Oblast)
                .Include(p => p.Predmet)
                .FirstOrDefaultAsync(m => m.ID == id);

            if (pitanje == null)
            {
                return NotFound();
            }
            Pitanje = pitanje;
           ViewData["OblastID"] = new SelectList(_context.Oblast, "ID", "Name");
           ViewData["PredmetID"] = new SelectList(_context.Predmet, "ID", "Name");
            var uniqueDifficulties = _context.Pitanje.Select(p => p.Difficulty).Distinct().ToList();
            DifficultyOptions = new SelectList(uniqueDifficulties);
            ViewData["Difficulty"] = DifficultyOptions;
            return Page();
        }

        
        public async Task<IActionResult> OnPostAsync()
        {
            /*if (!ModelState.IsValid)
            {
                return Page();
            }*/

            if (Upload != null)
            {
                var file = Path.Combine(_environment.ContentRootPath, "wwwroot\\images", Upload.FileName);
                using (var fileStream = new FileStream(file, FileMode.Create))
                {
                        await Upload.CopyToAsync(fileStream);

                        Pitanje.Image = Upload.FileName;
                    
                }
            }

            _context.Attach(Pitanje).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PitanjeExists(Pitanje.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Pitanja");
        }

        private bool PitanjeExists(int id)
        {
          return (_context.Pitanje?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

eUcionica/Pages/PitanjePage/Pitanja.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DataBaseContext;
using DatabaseEntityLib;

namespace eUcionica.Pages.PitanjePage
{
    public class PitanjeModel : PageModel
    {
        private readonly DataBaseContext.DB_Context_Class _context;

        [BindProperty]
        public string SearchText { get; set; }

        static bool reversePredmet = false;
        static bool reverseOblast = false;
        static bool reverseDiff = false;

        public PitanjeModel(DataBaseContext.DB_Context_Class context)
        {
            _context = context;
        }

        public IList<Pitanje> Pitanje { get;set; } = default!;

        public async Task OnGetAsync()
        {
            if (_context.Pitanje != null)
            {
                Pitanje = await _context.Pitanje
                .Include(p => p.Oblast)
                .Include(p => p.Predmet).ToListAsync();
            }
        }

        public async void OnGetSortByPredmet()
        {
            if (reversePredmet)
            {
                Pitanje = await _context.Pitanje.OrderBy(s => s.PredmetID)
                .Include(p => p.Oblast)
                .Include(p => p.Predmet).ToListAsync();
            }
            else
            {
                Pitanje = await _context.Pitanje.OrderByDescending(s => s.PredmetID)
               .Include(p => p.Oblast)
               .Include(p => p.Predmet).ToListAsync();
            }
            reversePredmet = !reversePredmet;
        }
        public async void OnGetSortByOblast()
        {
            if (reverseOblast)
            {
                Pitanje = await _context.Pitanje.OrderBy(s => s.OblastID)
                .Include(p => p.Oblast)
                .Include(p => p.Predmet).ToListAsync();
            }
            else
            {
                Pitanje = await _context.Pitanje.OrderByDescending(s => s.OblastID)
                .Include(p => p.Oblast)
                .Include(p => p.Predmet).ToListAsync();
            }
            reverseOblast = !reverseOblast;
        }
        public async void OnGetSortByDiff()
        {
            if (reverseDiff)
            {
                Pitanje = await _context.Pitanje.OrderBy(s => s.Difficulty)
                .Include(p => p.Oblast)
                .Include(p => p.Predmet).ToListAsync();
            }
            else
            {
                Pitanje = await _context.Pitanje.OrderByDescending(s => s.Difficulty)
                .Include(p => p.Oblast)
                .Include(p => p.Predmet).ToListAsync();
            }
                reverseDiff = !reverseDiff;
        }
        public async void OnPost()
        {
            if (SearchText == null)
            {
                Pitanje = await _context.Pitanje
                .Include(p => p.Oblast)
                .Include(p => p.Predmet).ToListAsync();
            }
            else
            {
                Pitanje = await _context.Pitanje.Where(s => EF.Functions.Like(s.Predmet.Name, $"%{SearchText}%") || EF.Functions.Like(s.Oblast.Name, $"%{SearchText}%") || EF.Functions.Like(s.Difficulty, $"%{SearchText}%"))
                .Include(p => p.Oblast)
                .Include(p => p.Predmet).ToListAsync();
            }
        }
    }
}

eUcionica/Pages/PredmetPage/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using DataBaseContext;
using DatabaseEntityLib;

namespace eUcionica.Pages.PredmetPage
{
    public class CreateModel : PageModel
    {
        private readonly DataBaseContext.DB_Context_Class _context;

        public CreateModel(DataBaseContext.DB_Context_Class context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Predmet Predmet { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (/*!ModelState.IsValid ||*/ _context.Predmet == null || Predmet == null)
            {
                return Page();
            }

            _context.Predmet.Add(Predmet);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Predmeti");
        }
    }
}

eUcionica/Pages/PitanjePage/Create.cshtml
@page
@model eUcionica.Pages.PitanjePage.CreateModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Креирање питања</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Pitanje.PredmetID" class="control-label">Предмет</label>
                <select asp-for="Pitanje.PredmetID" class="form-control" onchange="updateOblastDropdown()">
                    @foreach (var item in (IEnumerable<SelectListItem>)ViewData["PredmetID"])
                    {
                        <option value="@item.Value">@item.Text</option>
                    }
                </select>

            </div>
            <div class="form-group">
                <label asp-for="Pitanje.OblastID" class="control-label">Област</label>
                <select asp-for="Pitanje.OblastID" class="form-control" id="Pitanje_OblastID"></select>
            </div>
            <div class="form-group">
                <label asp-for="Pitanje.Difficulty" class="control-label">Тежина</label>
                <select asp-for="Pitanje.Difficulty" class="form-control" id="Pitanje_Difficulty">
                    @foreach (var item in (IEnumerable<SelectListItem>)ViewData["Difficulty"])
                    {
                        <option value="@item.Text">@item.Text</option>
                    }
                </select>
                <span asp-validation-for="Pitanje.Difficulty" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pitanje.Question" class="control-label">Питање</label>
                <input asp-for="Pitanje.Question" class="form-control" />
                <span asp-validation-for="Pitanje.Question" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Слика</label>
                <input type="file" asp-for="Upload" class="form-control" method="post" />
            </div>
            <div class="form-group">
                <label asp-for="Pitanje.Answer" class="control-label">Одговор</label>
                <input asp-for="Pitanje.Answer" class="form-control" />
                <span asp-validation-for="Pitanje.Answer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Креирај" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Pitanja">Назад на листу питања</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        function updateOblastDropdown() {
            var selectedPredmetID = document.getElementById("Pitanje_PredmetID").value;

            fetch(`/PitanjePage/Create?handler=IzaberiOblasti&predmetID=${selectedPredmetID}`)
                .then(response => response.json())
                .then(data => {
                    
                    var oblastDropdown = document.getElementById("Pitanje_OblastID");
                    oblastDropdown.innerHTML = "";

                    data.forEach(oblast => {
                        var option = document.createElement("option");
                        option.value = oblast.id;
                        option.text = oblast.name;
                        oblastDropdown.appendChild(option);
                    });
                })
                .catch(error => console.error("Error fetching data:", error));
        }
    </script>
}

eUcionica/Pages/PitanjePage/Delete.cshtml
@page
@model eUcionica.Pages.PitanjePage.DeleteModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Уклањање питања</h1>


<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @* @Html.DisplayNameFor(model => model.Pitanje.Predmet) *@
            Питање
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pitanje.Predmet.Name)
        </dd>
        <dt class="col-sm-2">
            @* @Html.DisplayNameFor(model => model.Pitanje.Oblast) *@
            Област
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pitanje.Oblast.Name)
        </dd>
        <dt class="col-sm-2">
            @* @Html.DisplayNameFor(model => model.Pitanje.Difficulty) *@
            Тежина
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pitanje.Difficulty)
        </dd>
        <dt class="col-sm-2">
            @* @Html.DisplayNameFor(model => model.Pitanje.Question) *@
            Текст питања
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pitanje.Question)
        </dd>
        <dt class="col-sm-2">
           @* @Html.DisplayNameFor(model => model.Pitanje.Answer) *@
           Одговор
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pitanje.Answer)
        </dd>
    </dl>
    <h5>Да ли сте сигурни да желите уклонити питање?</h5>
    <form method="post">
        <input type="hidden" asp-for="Pitanje.ID" />
        <input type="submit" value="Уклони" class="btn btn-danger" /> |
        <a asp-page="./Pitanja">Назад на листу питања</a>
    </form>
</div>

eUcionica/Pages/PitanjePage/Details.cshtml
@page
@model eUcionica.Pages.PitanjePage.DetailsModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Детаљи о питању</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @* @Html.DisplayNameFor(model => model.Pitanje.Predmet) *@
            Предмет
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pitanje.Predmet.Name)
        </dd>
        <dt class="col-sm-2">
            @* @Html.DisplayNameFor(model => model.Pitanje.Oblast) *@
            Област
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pitanje.Oblast.Name)
        </dd>
        <dt class="col-sm-2">
            @* @Html.DisplayNameFor(model => model.Pitanje.Difficulty) *@
            Тежина
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pitanje.Difficulty)
        </dd>
        <dt class="col-sm-2">
           @*  @Html.DisplayNameFor(model => model.Pitanje.Question) *@
           Питање
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pitanje.Question)
        </dd>
        <dt class="col-sm-2">
            @if (Model.Pitanje.Image != null)
            {
               <Slika/>
            }
        </dt>
        <dd class="col-sm-10">
            @if (Model.Pitanje.Image != null)
            {
                <img class="block" src="~/Images/@Model.Pitanje.Image" alt="" width="300" height="auto" />
            }
        </dd>
        <dt class="col-sm-2">
           @*  @Html.DisplayNameFor(model => model.Pitanje.Answer) *@
           Одговор
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pitanje.Answer)
        </dd>
        <hr />
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Pitanje?.ID">Измени</a> |
    <a asp-page="./Pitanja">Назад на листу питања</a>
</div>

eUcionica/Pages/PitanjePage/Edit.cshtml
@page
@model eUcionica.Pages.PitanjePage.EditModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Измена питања</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Pitanje.ID" />
            <div class="form-group">
                <label asp-for="Pitanje.PredmetID" class="control-label">Предмет</label>
                <select asp-for="Pitanje.PredmetID" class="form-control" asp-items="ViewBag.PredmetID"></select>
                <span asp-validation-for="Pitanje.PredmetID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pitanje.OblastID" class="control-label">Област</label>
                <select asp-for="Pitanje.OblastID" class="form-control" asp-items="ViewBag.OblastID"></select>
                <span asp-validation-for="Pitanje.OblastID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pitanje.Difficulty" class="control-label">Тежина</label>
                <select asp-for="Pitanje.Difficulty" class="form-control" id="Pitanje_Difficulty">
                    @foreach (var item in (IEnumerable<SelectListItem>)ViewData["Difficulty"])
                    {
                        <option value="@item.Text">@item.Text</option>
                    }
                </select>
                <span asp-validation-for="Pitanje.Difficulty" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pitanje.Question" class="control-label">Питање</label>
                <input asp-for="Pitanje.Question" class="form-control" />
                <span asp-validation-for="Pitanje.Question" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Слика</label>
                <input type="file" asp-for="Upload" class="form-control" method="post" />
                <span asp-validation-for="Upload" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pitanje.Answer" class="control-label">Одговор</label>
                <input asp-for="Pitanje.Answer" class="form-control" />
                <span asp-validation-for="Pitanje.Answer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сачувај" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Pitanja">Назад на листу питања</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

eUcionica/Pages/PitanjePage/Pitanja.cshtml
@page
@model eUcionica.Pages.PitanjePage.PitanjeModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Питања</h1>

<p>
    <a asp-page="Create">Састави питање</a>
</p>
<form method="post">
    <input type="text" asp-for="SearchText">
    <input type="submit" value="Pretraga">
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @*@Html.DisplayNameFor(model => model.Pitanje[0].Predmet)*@
                <a class="btn-outline-dark" asp-page-handler="SortByPredmet">Предмет</a>
            </th>
            <th>
               @* @Html.DisplayNameFor(model => model.Pitanje[0].Oblast) *@
                <a class="btn-outline-dark" asp-page-handler="SortByOblast">Област</a>
            </th>
            <th>
                @* @Html.DisplayNameFor(model => model.Pitanje[0].Difficulty) *@
                <a class="btn-outline-dark" asp-page-handler="SortByDiff">Тежина</a>
            </th>
            <th>
                Питање
            </th>
            <!--
            <th>
                Slika
            </th>
            <th>
                Odgovor
            </th>
            -->
            <th>Управљање</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Pitanje) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Predmet.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Oblast.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Difficulty)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Question)
            </td>
            <!--
            <td>
                    @if (item.Image != null)
                    {
                        <img class="block" src="~/Images/@item.Image" alt="" width="50" height="auto" />
                    }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Answer)
            </td>
            -->
            <td>
                <a asp-page="./Edit" asp-route-id="@item.ID">Измени</a> |
                <a asp-page="./Details" asp-route-id="@item.ID">Детаљи</a> |
                <a asp-page="./Delete" asp-route-id="@item.ID">Уклони</a>
            </td>
        </tr>
}
    </tbody>
</table>